"""
This modules creates an adapter that wraps an existing GNAgent instance and exposes a serializable config for GEPA.
"""

import asyncio
import json
import logging
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any, Dict, List

import dspy
from langchain_core.messages import SystemMessage

from all_config import *

PROMPT_NAMES = [
    "naturalize_prompt", "rephrase_prompt", "analyze_prompt", "check_prompt",
    "summarize_prompt", "synthesize_prompt", "split_prompt", "finalize_prompt",
    "sup_prompt1", "sup_prompt2", "plan_prompt", "refl_prompt",
]

agent = GNAgent(
    corpus_path=CORPUS_PATH,
    pcorpus_path=PCORPUS_PATH,
    db_path=DB_PATH,
    naturalize_prompt=naturalize_prompt,
    rephrase_prompt=rephrase_prompt,
    analyze_prompt=analyze_prompt,
    check_prompt=check_prompt,
    summarize_prompt=summarize_prompt,
    synthesize_prompt=synthesize_prompt,
    split_prompt=split_prompt,
    finalize_prompt=finalize_prompt,
    sup_prompt1=sup_prompt1,
    sup_prompt2=sup_prompt2,
    plan_prompt=plan_prompt,
    refl_prompt=refl_prompt,
)

def extract_config(agent) -> Dict[str, Any]:
    """Convert GNAgent to JSON-serialisable dict."""
    config: Dict[str, Any] = {}
    prompt_names = set(PROMPT_NAMES)

    allowed_fields = {"corpus_path", "pcorpus_path", "db_path"}
    for k, v in agent.__dict__.items():
        if k not in allowed_fields or k in prompt_names:
            continue
        config[k] = str(v) if isinstance(v, Path) else v

    config["prompts"] = {}
    for name in PROMPT_NAMES:
        obj = getattr(agent, name, None)
        if obj is not None:
            if isinstance(obj, SystemMessage):
                config["prompts"][name] = obj.content
            else:
                config["prompts"][name] = str(obj)
    
    return config

agent_config = extract_config(agent)


class GNAgentSig(dspy.Signature):
    query: str = dspy.InputField(desc="A natural language query for the GNAgent.")
    answer: str = dspy.OutputField(desc="Final answer generated by the GNAgent.")
    reasoning: str = dspy.OutputField(desc="Reasoning process leading to the answer.")
    
class GNAgentAdapter(dspy.Module):
    """
    DSPy-compatible wrapper for GNAgent.
    - Stores only JSON-serialisable config
    - Rebuilds GNAgent on every forward()
    - Exposes each prompt as a mutable `dspy.Predict`
    """

    def __init__(self, agent_config: Dict[str, Any]):
        super().__init__()
        self.config = agent_config
        self.executor = ThreadPoolExecutor(max_workers=1)

        # One Predict per prompt
        self.predictors: Dict[str, dspy.Predict] = {}
        for name in PROMPT_NAMES:
            init_text = agent_config["prompts"].get(name, "")
            pred = dspy.Predict(GNAgentSig)
            pred.prompt_text = init_text
            self.predictors[name] = pred
            setattr(self, name, pred)

    def build_agent(self) -> Any:
        base = {k: v for k, v in self.config.items() if k != "prompts"}

        valid_keys = {
            "corpus_path", "pcorpus_path", "db_path",
            "naturalize_prompt", "rephrase_prompt", "analyze_prompt", "check_prompt",
            "summarize_prompt", "synthesize_prompt", "split_prompt", "finalize_prompt",
            "sup_prompt1", "sup_prompt2", "plan_prompt", "refl_prompt"
        }
        base = {k: v for k, v in base.items() if k in valid_keys}

        for k in {"corpus_path", "pcorpus_path", "db_path"}:
            if k in base and isinstance(base[k], str):
                base[k] = Path(base[k])

        prompts = {}
        for name in PROMPT_NAMES:
            pred: dspy.Predict = self.predictors[name]
            text = getattr(pred, "prompt_text", "")
            prompts[name] = SystemMessage(content=text)

        return GNAgent(**base, **prompts)

    def run_handler(self, agent, query: str):
        return asyncio.run(agent.handler(query))

    def forward(self, **kwargs) -> dspy.Prediction:
        query = kwargs.get("query", "")
        agent = self.build_agent()
        answer, reasoning = self.executor.submit(self.run_handler, agent, query).result()
        return dspy.Prediction(
            answer=str(answer).strip(),
            reasoning=str(reasoning).strip() if reasoning else "",
        )

    def __call__(self, *args, **kwargs) -> dspy.Prediction:
        if args and isinstance(args[0], dspy.Example):
            return self.forward(query=args[0].query)
        return self.forward(**kwargs)

    def named_predictors(self):
        return [(name, self.predictors[name]) for name in PROMPT_NAMES]

    def save(self, path: str) -> None:
        data = {
            "config": self.config,
            "prompts": {name: pred.prompt_text for name, pred in self.predictors.items()}
        }
        Path(path).write_text(json.dumps(data, indent=2), encoding="utf-8")

    @classmethod
    def load(cls, path: str) -> "GNAgentAdapter":
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        adapter = cls(data["config"])
        for name, text in data["prompts"].items():
            pred: Predict = adapter.predictors[name]
            pred.prompt_text = text
        return adapter


# Create adapter for GNagent
adapter = GNAgentAdapter(agent_config)
